# Generated by Django 3.1.4 on 2020-12-24 11:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='last_scrapped',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 24, 12, 36, 11, 849537)),
        ),
        migrations.AddField(
            model_name='member',
            name='queue',
            field=models.CharField(default='unscrapped', max_length=50),
        ),
    ]
