# Generated by Django 3.1.4 on 2020-12-24 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0002_auto_20201224_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='last_scrapped',
            field=models.DateTimeField(default='24/12/2020 13:11:04'),
        ),
    ]
