# Generated by Django 3.1.4 on 2020-12-24 12:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0004_auto_20201224_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='last_scrapped',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 24, 13, 22, 59, 675639)),
        ),
    ]
