# Generated by Django 3.1.4 on 2020-12-29 19:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0005_auto_20201224_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='last_scrapped',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 20, 8, 34, 8, 8)),
        ),
    ]
