# Generated by Django 3.1.3 on 2021-01-03 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0006_auto_20201229_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='last_scrapped',
            field=models.CharField(default='unscrapped', max_length=50),
        ),
        migrations.AlterField(
            model_name='member',
            name='name',
            field=models.CharField(default='user', max_length=50),
        ),
        migrations.AlterField(
            model_name='member',
            name='user_name',
            field=models.CharField(default='user', max_length=50, unique=True),
        ),
    ]
