# Generated by Django 3.1.3 on 2021-01-15 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0007_auto_20210103_2103'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='queue',
            new_name='consumption_points',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='countdown',
            new_name='status',
        ),
    ]
